### ISSUE TITLE
Active student requests has duplicates.

### ISSUE THREAD

**Issue by sjhermanek** [Verardip/MDTProject2#24]
Active Student Requests

Theresa Froehlich: Calculus: Wednesday, April 26 2017. 1:00 PM - 2:00 PM
Theresa Froehlich: Calculus: Wednesday, April 26 2017. 1:00 PM - 2:00 PM
Theresa Froehlich: Calculus: Wednesday, April 26 2017. 1:00 PM - 2:00 PM
Theresa Froehlich: Calculus: Wednesday, April 26 2017. 1:00 PM - 2:00 PM

**Comment by Verardip** [comment]
Fixed. Thank you HashSet Data Structure :)
